version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80" # Frontend dostępny na porcie 8080
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Dodajemy konfigurację Nginx
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:80" # Backend (Laravel) dostępny na porcie 8081
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: diaryuser
      MYSQL_PASSWORD: diarypassword
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DEFAULT_AUTH: caching_sha2_password
    volumes:
      - ./backend/db:/var/lib/mysql
    ports:
      - "3306:3306" # MySQL na porcie 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
