version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80" # Frontend dostępny na porcie 8080
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:80" # Backend dostępny na porcie 8081
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diary
      MYSQL_USER: diaryuser
      MYSQL_PASSWORD: diarypassword
    volumes:
      - ./backend/db:/var/lib/mysql
    ports:
      - "3306:3306" # MySQL na porcie 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
